project_id = "qnxtxiqedohlqmgtsdnu"

[functions.stripe-webhook]
verify_jwt = false

[functions.payout]
verify_jwt = false

[functions.sms]
verify_jwt = false

[functions.stripe-billing]
verify_jwt = false

[functions.send-alert]
verify_jwt = false

[functions.calculate-distance]
verify_jwt = false

[functions.job-assignment-algorithm]
verify_jwt = false

[functions.send-job-notification]
verify_jwt = false

[functions.job-status-manager]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.notify-drivers-new-job]
verify_jwt = false

[functions.record-swap-usage]
verify_jwt = false

[functions.google-maps-config]
verify_jwt = false