version = 1

exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "build/**",
  ".next/**",
  "coverage/**",
  "*.snap",
  "**/*.spec.*",
  "**/*.test.*",
  "**/__tests__/**",
  "**/__mocks__/**",
  "**/*.stories.*",
  ".storybook/**",
  "cypress/**",
  "playwright/**"
]

test_patterns = [
  "**/*.spec.*",
  "**/*.test.*",
  "**/__tests__/**"
]

[[analyzers]]
name = "javascript"
enabled = true
  [[transformers]]
  name = "prettier"
  enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true
