// This file is automatically generated. Edits are safe but may be overwritten by generators.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Prefer runtime env (Vite prefix for client builds). Fall back to the previous hard-coded values
// so existing deploys keep working until you update envs.
const SUPABASE_URL =
  (typeof process !== "undefined" &&
    (process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL)) ||
  "https://qnxtxiqedohlqmgtsdnu.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  (typeof process !== "undefined" &&
    (process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_ANON_KEY ||
      process.env.SUPABASE_KEY)) ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFueHR4aXFlZG9obHFtZ3RzZG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTM4MTcsImV4cCI6MjA3MzU2OTgxN30.oOIqGw4lm30iRtMjTD8uZIOM8vUfYEVejLISZdJRl4M";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Warning: SUPABASE_URL or SUPABASE_ANON_KEY is not set in environment variables.",
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
