// This file is automatically generated. Edits are safe but may be overwritten by generators.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Use Vite's import.meta.env for client-side environment variables
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://iesaadkusjmwiseichuu.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllc2FhZGt1c2ptd2lzZWljaHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMjYyMDcsImV4cCI6MjA3NjkwMjIwN30.ykmSlQEJF3hPU7ZtrDxR1HUHGJmvoqiiGea6Zarq7s4";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Warning: SUPABASE_URL or SUPABASE_ANON_KEY is not set in environment variables.",
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
